### PR TITLE
Go 1.8 supports bool type in binary.{Read,Write}

### PR DESCRIPTION
**Pull request by bradleyfalzon**
https://github.com/golang/go/issues/16856

/cc @dgryski

### CODE REVIEW

**Comment by dgryski** [comment]
I wonder if we want to somehow flag this as "go version <1.8".  That way people who are still on 1.7 don't get false-negatives.

**Comment by bradleyfalzon** [comment]
~I do agree, but there's also the ignore flags now, so I think they could just ignore the broader check: https://github.com/dominikh/go-staticcheck#ignoring-checks~

EDIT: @dominikh pointed out you can't ignore a false negative, so please excuse my complete lack of thinking.

**Comment by bradleyfalzon** [comment]
Note, I didn't implement the additional suggestion of @dgryski to detect now pointless bool to int conversions that previously would've been used to work around the lack of bool support, such as in: https://github.com/hybridgroup/gobot/blob/94d78d777abc68bf4828a7fc1b68ef32e006f75e/platforms/bebop/client/client.go#L621

**Comment by dominikh** [comment]
@dgryski I'm not concerned with a rare false negative in an already rarely matching check in an outdated version of Go. And in general I support (and require) the latest version of Go. For everything else there's vendoring. (That'll become more important when gosimple is to point out unnecessary conversions, which will not be correct for Go <1.8.

@bradleyfalzon I'll merge the PR once Go 1.8 has been released.

**Comment by bradleyfalzon** [comment]
See https://github.com/dominikh/go-tools/pull/4

**Pull request closed without merging**
